
const events = [
    { title: "Porch Fest", venue: "Neighborhood porches", date: "2026-10-25", time: "1:00 PM", local: true, audience: "all", category: "music", genre: "all", price: "Free", description: "Local bands play from front porches around the neighborhood. Walk from porch to porch and catch country, rap, indie and rock sets all afternoon." },
    { title: "Porch Light Country Night", venue: "Georgia Theatre", date: "2026-10-02", time: "8:00 PM", local: true, audience: "friends", category: "music", genre: "country" },
    { title: "Classic City Rap Cypher", venue: "40 Watt Club", date: "2026-10-03", time: "9:00 PM", local: true, audience: "solo", category: "music", genre: "rap" },
    { title: "Kudzu Indie Showcase", venue: "Flicker Theatre & Bar", date: "2026-10-03", time: "8:30 PM", local: true, audience: "solo", category: "music", genre: "indie" },
    { title: "Red Clay Rock Revival", venue: "Hendershot's", date: "2026-10-04", time: "9:00 PM", local: true, audience: "solo", category: "music", genre: "rock" },
    { title: "Sunday Family Pizza Night", venue: "Little Italy", date: "2026-10-04", time: "5:00 PM", local: true, audience: "family", category: "restaurant" },
    { title: "Intro to Podcasting", venue: "Athens-Clarke County Library", date: "2026-10-05", time: "6:00 PM", local: true, audience: "solo", category: "seminar" },
    { title: "Open Mic Comedy", venue: "Allgood Lounge", date: "2026-10-06", time: "8:00 PM", local: true, audience: "solo", category: "comedy" },
    { title: "Wine & Small Plates Pairing", venue: "The National", date: "2026-10-07", time: "7:00 PM", local: true, audience: "date", category: "restaurant" },
    { title: "Nashville Honky-Tonk Tour", venue: "Georgia Theatre", date: "2026-10-08", time: "8:00 PM", local: false, audience: "solo", category: "music", genre: "country" },
    { title: "Small Business Marketing Workshop", venue: "Athens Downtown Library", date: "2026-10-08", time: "6:30 PM", local: true, audience: "solo", category: "seminar" },
    { title: "Date Night Jazzy Indie Duo", venue: "Ciné Barcafé", date: "2026-10-09", time: "8:00 PM", local: true, audience: "date", category: "music", genre: "indie" },
    { title: "Stand-Up Fridays", venue: "Normaltown Comedy Room", date: "2026-10-09", time: "9:00 PM", local: true, audience: "date", category: "comedy" },
    { title: "Atlanta Underground Rap Night", venue: "40 Watt Club", date: "2026-10-10", time: "9:00 PM", local: false, audience: "solo", category: "music", genre: "rap" },
    { title: "Family Fall Festival Concert", venue: "Bishop Park", date: "2026-10-10", time: "2:00 PM", local: true, audience: "family", category: "music", genre: "country" },
    { title: "Farm-to-Table Chef Dinner", venue: "Farm 255", date: "2026-10-11", time: "6:30 PM", local: true, audience: "date", category: "restaurant" },
    { title: "Brunch & Bluegrass-Country Jam", venue: "Mama's Boy", date: "2026-10-11", time: "11:00 AM", local: true, audience: "family", category: "music", genre: "country" },
    { title: "Music Business 101", venue: "UGA Georgia Center", date: "2026-10-12", time: "5:30 PM", local: false, audience: "solo", category: "seminar" },
    { title: "Trivia Night with Comedy Hosts", venue: "Trappeze Pub", date: "2026-10-13", time: "7:30 PM", local: true, audience: "friends", category: "comedy" },
    { title: "Garage Rock Tuesday", venue: "Hendershot's", date: "2026-10-13", time: "9:00 PM", local: true, audience: "solo", category: "music", genre: "rock" },
    { title: "Taco Tuesday Live Music", venue: "Taqueria del Sol", date: "2026-10-13", time: "6:00 PM", local: true, audience: "friends", category: "restaurant" },
    { title: "Indie Folk Candlelight Set", venue: "Georgia Theatre Rooftop", date: "2026-10-15", time: "7:30 PM", local: true, audience: "date", category: "music", genre: "indie" },
    { title: "Touring Headliner Comedy Tour", venue: "Classic Center", date: "2026-10-16", time: "8:00 PM", local: false, audience: "date", category: "comedy" },
    { title: "Hip-Hop Block Party", venue: "Hot Corner", date: "2026-10-17", time: "3:00 PM", local: true, audience: "family", category: "music", genre: "rap" },
    { title: "Heavy Riffs Night", venue: "40 Watt Club", date: "2026-10-17", time: "9:00 PM", local: false, audience: "solo", category: "music", genre: "rock" },
    { title: "Beginner Home Gardening Seminar", venue: "State Botanical Garden", date: "2026-10-18", time: "1:00 PM", local: true, audience: "family", category: "seminar" },
    { title: "Sunday Supper Club", venue: "Five & Ten", date: "2026-10-18", time: "6:00 PM", local: true, audience: "date", category: "restaurant" },
    { title: "Kids Comedy Magic Show", venue: "Athens Community Theatre", date: "2026-10-24", time: "2:00 PM", local: true, audience: "family", category: "comedy" },
    { title: "Country Line Dancing Night", venue: "Buvez", date: "2026-10-23", time: "8:00 PM", local: true, audience: "friends", category: "music", genre: "country" },
    { title: "Halloween Indie Dance Party", venue: "Flicker Theatre & Bar", date: "2026-10-30", time: "9:00 PM", local: true, audience: "friends", category: "music", genre: "indie" },
    { title: "Spooky Rock Tribute Show", venue: "Georgia Theatre", date: "2026-10-31", time: "8:00 PM", local: true, audience: "friends", category: "music", genre: "rock" },
    { title: "Haunted Dinner Mystery", venue: "The Place", date: "2026-10-31", time: "7:00 PM", local: true, audience: "date", category: "restaurant" },
    { title: "Resume & Interview Seminar", venue: "UGA Career Center", date: "2026-10-21", time: "4:00 PM", local: false, audience: "solo", category: "seminar" },
    { title: "Rap Songwriting Workshop", venue: "Athens Creative Hub", date: "2026-10-22", time: "6:00 PM", local: true, audience: "friends", category: "seminar" }
];
